### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by shibaobun** [yupix/MiPA#5]
Misskey may have changed something about their API, but I'm getting this error in Ente's misskey-ebooks-bot that uses MiPA with Misskey v12.112.3:
```
misskey-ebooks  | connections: ['[(<aiohttp.client_proto.ResponseHandler object at address>, numbers)]']            
misskey-ebooks  | connector: <aiohttp.connector.TCPConnector object at address>                                              
misskey-ebooks  | Traceback (most recent call last):                                                                                
misskey-ebooks  |   File "/usr/src/app/rdbot.py", line 68, in <module>                                                              
misskey-ebooks  |     asyncio.run(bot.start(url, token))                                                                            
misskey-ebooks  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run                                            
misskey-ebooks  |     return loop.run_until_complete(main)                                                                          
misskey-ebooks  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete                        
misskey-ebooks  |     return future.result()                                                                                        
misskey-ebooks  |   File "/usr/local/lib/python3.10/site-packages/mipa/client.py", line 257, in start                               
misskey-ebooks  |     await self.login(token, origin_url)                                                                           
misskey-ebooks  |   File "/usr/local/lib/python3.10/site-packages/mipa/client.py", line 189, in login                               
misskey-ebooks  |     await api.http.login()                                                                                        
misskey-ebooks  |   File "/usr/local/lib/python3.10/site-packages/mipac/http.py", line 102, in login                                
misskey-ebooks  |     data = await self.request(Route('POST', '/api/i'), auth=True)                                                 
misskey-ebooks  |   File "/usr/local/lib/python3.10/site-packages/mipac/http.py", line 95, in request                               
misskey-ebooks  |     raise APIError(data)                                                                                          
misskey-ebooks  | mipac.exception.APIError: None                                                                                    
misskey-ebooks  | Unclosed client session                                                                                           
misskey-ebooks  | client_session: <aiohttp.client.ClientSession object at address>                                           
misskey-ebooks  | Unclosed connector                                                                                                
misskey-ebooks  | connections: ['[(<aiohttp.client_proto.ResponseHandler object at address>, numbers)]']            
misskey-ebooks  | connector: <aiohttp.connector.TCPConnector object at address>                                              
misskey-ebooks  | Traceback (most recent call last):                                                                                
misskey-ebooks  |   File "/usr/src/app/rdbot.py", line 68, in <module>                                                              
misskey-ebooks  |     asyncio.run(bot.start(url, token))                                                                            
misskey-ebooks  |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run                                            
misskey-ebooks  |     return loop.run_until_complete(main)                                                                          
misskey-ebooks  |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete                        
misskey-ebooks  |     return future.result()                                                                                        
misskey-ebooks  |   File "/usr/local/lib/python3.10/site-packages/mipa/client.py", line 257, in start                               
misskey-ebooks  |     await self.login(token, origin_url)                                                                           
misskey-ebooks  |   File "/usr/local/lib/python3.10/site-packages/mipa/client.py", line 190, in login                               
misskey-ebooks  |     self.user = await api.action.get_me()                                                                         
misskey-ebooks  |   File "/usr/local/lib/python3.10/site-packages/mipac/manager/client.py", line 42, in get_me                      
misskey-ebooks  |     return await self.user.action.get_me()                                                                        
misskey-ebooks  |   File "/usr/local/lib/python3.10/site-packages/mipac/actions/user.py", line 45, in get_me                        
misskey-ebooks  |     return User(RawUser(res), client=self.__client)                                                               
misskey-ebooks  |   File "/usr/local/lib/python3.10/site-packages/mipac/core/models/user.py", line 150, in __init__                 
misskey-ebooks  |     self.id: str = data['user_id'] if data.get('user_id') else data['id']                                         
misskey-ebooks  | AttributeError: 'NoneType' object has no attribute 'get'                                                          
misskey-ebooks  | Unclosed client session                                                                                           
misskey-ebooks  | client_session: <aiohttp.client.ClientSession object at address>                                           
misskey-ebooks  | Unclosed connector                                                                                                
misskey-ebooks  | connections: ['[(<aiohttp.client_proto.ResponseHandler object at address>, numbers)]']           
misskey-ebooks  | connector: <aiohttp.connector.TCPConnector object at address>
```

**Comment by yupix** [comment]
We tested with the following simple code Interestingly, the authentication did not seem to work with the old token for some reason. So I regenerated the token and it worked. Please try this method and see if the problem occurs again.

```python
import asyncio
from mipa.ext.commands import Bot

class MyBot(Bot):
    def __init__(self):
        super().__init__()
    
    async def on_ready(self, ws):
        print(self.user.name)

if __name__ == '__main__':
    bot = MyBot()
    asyncio.run(bot.start('url', 'token'))
```
